// <auto-generated />
using System;
using DataLayer.DBContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DataLayer.Migrations
{
    [DbContext(typeof(AccountDbContext))]
    [Migration("20220313124755_EditTblSubCategory")]
    partial class EditTblSubCategory
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("DataLayer.Tables.TblCategory", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("cat_name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("tblCategory");
                });

            modelBuilder.Entity("DataLayer.Tables.TblItem", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("bar_code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("profit")
                        .HasColumnType("real");

                    b.Property<float>("purchase_price")
                        .HasColumnType("real");

                    b.Property<float>("sales_price")
                        .HasColumnType("real");

                    b.Property<int>("subcat_id")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("tblItem");
                });

            modelBuilder.Entity("DataLayer.Tables.TblSubCategory", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int?>("cat_id")
                        .HasColumnType("int");

                    b.Property<string>("subcat_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("tblCategoryid")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("tblCategoryid");

                    b.ToTable("tblSubCategory");
                });

            modelBuilder.Entity("DataLayer.Tables.TblUser", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("user_name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("tblUser");
                });

            modelBuilder.Entity("DataLayer.Tables.TblSubCategory", b =>
                {
                    b.HasOne("DataLayer.Tables.TblCategory", "tblCategory")
                        .WithMany("tblSubCategory")
                        .HasForeignKey("tblCategoryid");

                    b.Navigation("tblCategory");
                });

            modelBuilder.Entity("DataLayer.Tables.TblCategory", b =>
                {
                    b.Navigation("tblSubCategory");
                });
#pragma warning restore 612, 618
        }
    }
}
